name: 'Fetch Quote of the Day'
description: 'Fetches an inspirational quote with author and image from various quote APIs'
author: 'nclsbayona'

branding:
  icon: 'message-circle'
  color: 'blue'

outputs:
  quote:
    description: 'The quote text'
  author:
    description: 'The quote author'
  image:
    description: 'URL of the author image'

runs:
  using: 'docker'
  image: 'Dockerfile'