#!/bin/bash
set -euo pipefail

OUTPUT_DIR="${INPUT_OUTPUT_DIR}"
SCREENSHOT_NAME="${INPUT_SCREENSHOT_NAME}"
PAGE_URL="${INPUT_PAGE_URL}"
ELEMENT_ID="${INPUT_ELEMENT_ID}"
TIMEOUT="${INPUT_TIMEOUT}"

mkdir -p "$OUTPUT_DIR"

export PAGE_URL="$PAGE_URL"
export ELEMENT_ID="$ELEMENT_ID"
export OUTPUT_DIR="$OUTPUT_DIR"
export SCREENSHOT_NAME="$SCREENSHOT_NAME"
export TIMEOUT="$TIMEOUT"

node /opt/screenshot.js

echo "screenshot_png=$OUTPUT_DIR/$SCREENSHOT_NAME" >> "$GITHUB_OUTPUT"
