name: "Test sitemap with k6 and export dashboard"
description: "Run k6 against webpage's sitemap, export HTML dashboard, and create a PNG screenshot"

inputs:
  base_url:
    required: true
    description: "Base URL (e.g. https://yourdomain.com)"
  sitemap_url:
    required: false
    default: ""
    description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
  vus:
    required: false
    default: "5"
    description: "Number of virtual users (VUs) to simulate"
  duration:
    required: false
    default: "1m"
    description: "Duration of the test (e.g. 30s, 1m, 5m)"
  url_limit:
    required: false
    default: "500"
    description: "Maximum number of URLs to test from the sitemap"
  redirect_limit:
    required: false
    default: "5"
    description: "Maximum number of redirects to follow per URL"
  test_mode:
    required: false
    default: "vus"
    description: "The test mode to run (vus (constant VUs for DURATION (classic concurrency test) , rate (constant arrival rate for DURATION))"

outputs:
  dashboard_html:
    description: "The HTML dashboard generated by k6"
    value: "artifacts/k6-report.html"
  dashboard_png:
    description: "PNG screenshot of the HTML dashboard"
    value: "artifacts/images/k6-dashboard.png"


runs:
  using: "composite"
  steps:
    - name: Run k6 (export HTML dashboard)
      shell: bash
      env:
        BASE_URL: ${{ inputs.base_url }}
        SITEMAP_URL: ${{ inputs.sitemap_url }}
        VUS: ${{ inputs.vus }}
        DURATION: ${{ inputs.duration }}
        URL_LIMIT: ${{ inputs.url_limit }}
        REDIRECT_LIMIT: ${{ inputs.redirect_limit }}
        TEST_MODE: ${{ inputs.test_mode }}
        K6_WEB_DASHBOARD: "true"
        K6_WEB_DASHBOARD_EXPORT: "artifacts/k6-report.html"
      run: |
        mkdir -p "artifacts"
        k6 run /opt/analyze-sitemap.js

    - name: Screenshot dashboard to PNG
      shell: bash
      env:
        REPORT_HTML: "artifacts/k6-report.html"
        OUT_DIR: "artifacts/images"
      run: |
        node /opt/load-dashboard.mjs

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: k6-sitemap-results
        path: artifacts
