name: Create webpage GIF
run-name: ${{ github.workflow }} (#${{ github.run_id }})

on:
  workflow_call:
    inputs:
      base_dir:
        type: string
        description: "Directory where the artifacts should be stored"
        required: false
        default: "artifacts"
      wait_for_merge:
        type: boolean
        description: "Whether to wait for the PR to be merged before proceeding"
        required: false
        default: true
  workflow_dispatch:
    inputs:
      BASE_DIR:
        type: string
        description: "Directory where the artifacts should be stored"
        required: false
        default: "artifacts"
      WAIT_FOR_MERGE:
        type: boolean
        description: "Whether to wait for the PR to be merged before proceeding"
        required: false
        default: false

env:
  PR_BRANCH: update-website-gif-${{ github.run_id }}
  DIRECTORY: ${{ (github.event_name == 'workflow_call' && github.event.inputs.base_dir) || (github.event_name == 'workflow_dispatch' && inputs.base_dir) }}/images

jobs:
  make-gif:
    name: Make GIF
    runs-on: ubuntu-latest
    outputs:
      pr_branch: ${{ env.PR_BRANCH }}
      pr_url: ${{ steps.create_pr.outputs.pull-request-url }}
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1
    - uses: actions/checkout@v6.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}
        persist-credentials: false

    - name: Create directory for GIF
      run: |
        mkdir -p ${{ env.DIRECTORY }}

    - name: Website to file
      uses: PabloLec/website-to-gif@2.1.5
      with:
        url: "https://nclsbayona.github.io"
        scroll_step: 100
        save_path: "/${{ env.DIRECTORY }}"

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v8.1.1
      with:
        token: ${{ secrets.PR_TOKEN }}
        branch: ${{ env.PR_BRANCH }}
        base: main
        delete-branch: true
        title: "docs: :memo: Update website gif"
        body: "Automated update: refresh website gif in ${{ env.DIRECTORY }}"

  wait-for-gif:
    needs: make-gif
    runs-on: ubuntu-latest
    name: Wait for GIF PR to be merged
    steps:
      - name: Debug PR outputs
        run: |
          echo "number=${{ needs.make-gif.outputs.pr_number }}"
          echo "url=${{ needs.make-gif.outputs.pr_url }}"

      - name: Wait for PR to be merged
        if: ${{ (github.event_name == 'workflow_call' && github.event.inputs.wait_for_merge) || (github.event_name == 'workflow_dispatch' && inputs.WAIT_FOR_MERGE) }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number("${{ needs.make-gif.outputs.pr_number }}");

            if (!prNumber || Number.isNaN(prNumber)) {
              core.setFailed(
                "No PR number received. Check."
              );
              return;
            }

            console.log(`Waiting for PR #${prNumber} to be merged`);

            while (true) {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });

              if (pr.merged) {
                console.log(`PR #${prNumber} has been merged!`);
                break;
              }

              console.log(`PR #${prNumber} is not merged yet. Checking again in 90 seconds...`);
              await new Promise(resolve => setTimeout(resolve, 90000));
            }
