name: Purge old runs
run-name: ${{ github.workflow }} (#${{ github.run_id }})

on:
  schedule:
    - cron: "0 9 1,10,20 * *"
  workflow_dispatch:

permissions:
  actions: write
  
jobs:
  build:
    name: Purge old runs
    runs-on: ubuntu-latest
    steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Delete old
        uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: 5
          keep-latest: 2
