name: Keep repository active

on:
  schedule:
    - cron: '0 0 */15 * *'

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Configure Git
      run: |
        git config user.name 'Commit bot'
        git config user.email 'noreply@my-commit-bot.com'

    - name: Create an empty commit and push
      run: |
        git commit --allow-empty -m "Empty commit" -m "This commit is empty to prevent GitHub Actions from being disabled due to inactivity."
        git push origin master