name: Check Site Performance with Page Speed Insights

on: 
  workflow_dispatch:
  schedule:
  - cron:  '0 5 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run Page Speed Insights (Mobile)
      uses: mattorb/psi-action@v1
      id: psi_mobile
      with:
        threshold: 50
        url: "https://nclsbayona.github.io"
        strategy: mobile
    - name: Run Page Speed Insights (Desktop)
      uses: mattorb/psi-action@v1
      id: psi_desktop
      with:
        threshold: 50
        url: "https://nclsbayona.github.io"
        strategy: desktop