name: Security scan

on:
  schedule:
  - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  analyze:
    name: Analyze 🔎 (${{ matrix.language }})
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
        - language: go
          build-mode: autobuild
        - language: javascript
          build-mode: autobuild
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
          persist-credentials: false

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:${{matrix.language}}"

  page-scan:
    name: Scan with ZAP 💬
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1
    - name: ZAP Full Scan
      uses: zaproxy/action-baseline@v0.15.0
      with:
        target: 'https://nclsbayona.github.io'
        artifact_name: 'full-report'
        allow_issue_writing: false

  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      #- name: Configure monitor
      #  uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0

  gitleaks:
    name: Run Gitleaks 🗝️
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    #  - name: Configure monitor
    #    uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--verbose"

  trivy:
    name: Run Trivy 🧐
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
    #  - name: Configure monitor
    #    uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.35.0
        with:
          exit-code: 0
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
