name: ZAP scan

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  baseline:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: 'https://nclsbayona.github.io'

  full:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'https://nclsbayona.github.io'