name: Load test sitemap

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        description: "Base URL (e.g. https://yourdomain.com)"
        required: true
      sitemap_url:
        type: string
        description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
        required: false
        default: ""
      users:
        type: string
        description: "Number of virtual users (VUs) to simulate"
        required: false
        default: "5"
      duration:
        type: string
        description: "Duration of the test (e.g. 30s, 1m, 5m)"
        required: false
        default: "1m"
      url_limit:
        type: string
        description: "Maximum number of URLs to test from the sitemap"
        required: false
        default: "500"
      redirect_limit:
        type: string
        description: "Maximum number of redirects to follow per URL"
        required: false
        default: "5"
      test_mode:
        type: string
        description: "The test mode to run (vus (constant VUs for DURATION (classic concurrency test) , rate (constant arrival rate for DURATION))"
        required: false
        default: "vus"
    

  workflow_dispatch:
    inputs:
      BASE_URL:
        description: "Base URL (e.g. https://yourdomain.com)"
        required: true
      SITEMAP_URL:
        description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
        required: false
        default: ""
      VUS:
        description: "Number of virtual users (VUs) to simulate"
        required: false
        default: "5"
      DURATION:
        description: "Duration of the test (e.g. 30s, 1m, 5m)"
        required: false
        default: "1m"
      URL_LIMIT:
        description: "Maximum number of URLs to test from the sitemap"
        required: false
        default: "500"
      REDIRECT_LIMIT:
        description: "Maximum number of redirects to follow per URL"
        required: false
        default: "5"
      TEST_MODE:
        description: "The test mode to run (vus (constant VUs for DURATION (classic concurrency test) , rate (constant arrival rate for DURATION))"
        required: false
        default: "vus"
    
  # schedule:
  # - cron: "0 3 * * 0" # Weekly on Sundays at 03:00 UTC

  push:
    branches: [main]
    paths:
      - '.github/workflows/test-sitemap.yml'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.actor }}/k6-playwright:latest

    steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: Check Inputs
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "inputs=${{ toJson(inputs) }}"
          echo "github.event=${{ toJson(github.event) }}"

      - uses: actions/checkout@v6
        with:
          persist-credentials: true

      - name: Run sitemap action
        id: test
        uses: ./.github/actions/k6-sitemap
        with:
          base_url: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.BASE_URL) || (github.event_name == 'schedule' && 'https://nclsbayona.github.io') || (github.event_name == 'workflow_dispatch' && inputs.base_url) || (github.event_name == 'push' && 'https://nclsbayona.github.io') || (github.event_name == 'deployment' && inputs.base_url) }}
          sitemap_url: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.SITEMAP_URL) || (github.event_name == 'schedule' && 'https://nclsbayona.github.io/sitemap.xml') || (github.event_name == 'workflow_dispatch' && inputs.sitemap_url) || (github.event_name == 'push' && 'https://nclsbayona.github.io/sitemap.xml') || (github.event_name == 'deployment' && inputs.sitemap_url) }}
          vus: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.VUS) || (github.event_name == 'schedule' && '50') || (github.event_name == 'workflow_dispatch' && inputs.users) || (github.event_name == 'push' && '10') || (github.event_name == 'deployment' && inputs.users) }}
          duration: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.DURATION) || (github.event_name == 'schedule' && '5m') || (github.event_name == 'workflow_dispatch' && inputs.duration) || (github.event_name == 'push' && '30s') || (github.event_name == 'deployment' && inputs.duration) }}
          redirect_limit: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.REDIRECT_LIMIT) || (github.event_name == 'schedule' && '5') || (github.event_name == 'workflow_dispatch' && inputs.redirect_limit) || (github.event_name == 'push' && '5') || (github.event_name == 'deployment' && inputs.redirect_limit) }}
          test_mode: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.TEST_MODE) || (github.event_name == 'schedule' && 'rate') || (github.event_name == 'workflow_dispatch' && inputs.test_mode) || (github.event_name == 'push' && 'rate') || (github.event_name == 'deployment' && inputs.test_mode) }}
          url_limit: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.URL_LIMIT) || (github.event_name == 'schedule' && '500') || (github.event_name == 'workflow_dispatch' && inputs.url_limit) || (github.event_name == 'push' && '500') || (github.event_name == 'deployment' && inputs.url_limit) }}

      - name: Get dashboard variables
        id: dashboard
        run: |
          echo "The HTML is available at ${{ steps.test.outputs.dashboard_html }}"
          echo "The PNG is available at ${{ steps.test.outputs.dashboard_png }}"

      - name: Download dashboard artifacts
        id: download_png
        uses: actions/download-artifact@v7
        with:
          name: ${{ steps.test.outputs.artifact_name }}

      - name: Add safe directory
        run: |
          git config --global --add safe.directory /__w/nclsbayona.github.io/nclsbayona.github.io

      - name: Commit dashboard PNG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: :memo: Update load test dashboard"