name: Load test sitemap
run-name: ${{ github.workflow }} (#${{ github.run_id }})

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        description: "Base URL (e.g. https://yourdomain.com)"
        required: true
      sitemap_url:
        type: string
        description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
        required: false
        default: ""
      users:
        type: string
        description: "Number of virtual users (VUs) to simulate"
        required: false
        default: "5"
      duration:
        type: string
        description: "Duration of the test (e.g. 30s, 1m, 5m)"
        required: false
        default: "1m"
      url_limit:
        type: string
        description: "Maximum number of URLs to test from the sitemap"
        required: false
        default: "500"
      http_timeout:
        type: string
        description: "The timeout for HTTP"
        required: false
        default: "5s"
      base_output_dir:
        type: string
        description: "Directory where the HTML dashboard and PNG screenshot will be saved (default: results)"
        required: true
    

  workflow_dispatch:
    inputs:
      BASE_URL:
        description: "Base URL (e.g. https://yourdomain.com)"
        required: true
      SITEMAP_URL:
        description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
        required: false
        default: ""
      VUS:
        description: "Number of virtual users (VUs) to simulate"
        required: false
        default: "5"
      DURATION:
        description: "Duration of the test (e.g. 30s, 1m, 5m)"
        required: false
        default: "1m"
      URL_LIMIT:
        description: "Maximum number of URLs to test from the sitemap"
        required: false
        default: "500"
      HTTP_TIMEOUT:
        type: string
        description: "The timeout for HTTP"
        required: false
        default: "5s"
      BASE_OUTPUT_DIR:
        description: "Directory where the HTML dashboard and PNG screenshot will be saved (default: results)"
        required: false
        default: "artifacts"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run sitemap analysis
    permissions:
      contents: write
      pull-requests: write
    env:
      PR_BRANCH: "update-gif-${{ github.run_id }}"
      ARTIFACTS_DIR: ${{ github.event.inputs.BASE_OUTPUT_DIR || inputs.base_output_dir }}
    steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - uses: actions/checkout@v7.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Create directory for Artifacts
        run: |
          mkdir -p ${{ env.ARTIFACTS_DIR }}

      - name: Run sitemap action
        id: test
        uses: ./.github/actions/k6-sitemap
        with:
          base_output_dir: ${{ env.ARTIFACTS_DIR }}
          base_url: ${{ github.event.inputs.BASE_URL || inputs.base_url }}
          sitemap_url: ${{ github.event.inputs.SITEMAP_URL || inputs.sitemap_url }}
          vus: ${{ github.event.inputs.VUS || inputs.users }}
          duration: ${{ github.event.inputs.DURATION || inputs.duration }}
          http_timeout: ${{ github.event.inputs.HTTP_TIMEOUT || inputs.http_timeout }}
          url_limit: ${{ github.event.inputs.URL_LIMIT || inputs.url_limit }}

      - name: Upload reports
        if: success()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: k6-sitemap-reports-${{ github.run_id }}
          path: ${{ env.ARTIFACTS_DIR }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          token: ${{ secrets.PR_TOKEN }}
          branch: ${{ env.PR_BRANCH }}
          base: main
          delete-branch: true
          commit-message: "chore: Update"
          title: "docs: :memo: Update loadtest image"
          body: "Automated update: refresh loadtest in directory ${{ env.ARTIFACTS_DIR }}"
