name: Load test sitemap

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        description: "Base URL (e.g. https://yourdomain.com)"
        required: true
      sitemap_url:
        type: string
        description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
        required: false
        default: ""
      users:
        type: string
        description: "Number of virtual users (VUs) to simulate"
        required: false
        default: "5"
      duration:
        type: string
        description: "Duration of the test (e.g. 30s, 1m, 5m)"
        required: false
        default: "1m"
      url_limit:
        type: string
        description: "Maximum number of URLs to test from the sitemap"
        required: false
        default: "500"
      http_timeout:
        type: string
        description: "The timeout for HTTP"
        required: false
        default: "5s"
    

  workflow_dispatch:
    inputs:
      BASE_URL:
        description: "Base URL (e.g. https://yourdomain.com)"
        required: true
      SITEMAP_URL:
        description: "Sitemap URL (defaults to BASE_URL/sitemap.xml)"
        required: false
        default: ""
      VUS:
        description: "Number of virtual users (VUs) to simulate"
        required: false
        default: "5"
      DURATION:
        description: "Duration of the test (e.g. 30s, 1m, 5m)"
        required: false
        default: "1m"
      URL_LIMIT:
        description: "Maximum number of URLs to test from the sitemap"
        required: false
        default: "500"
      HTTP_TIMEOUT:
        type: string
        description: "The timeout for HTTP"
        required: false
        default: "5s"
    
  # schedule:
  # - cron: "0 3 * * 0" # Weekly on Sundays at 03:00 UTC

  push:
    branches: [main]
    paths:
      - '.github/workflows/test-sitemap.yml'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.actor }}/k6-playwright:latest

    steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

      # - name: Check Inputs
      #   run: |
      #     echo "event_name=${{ github.event_name }}"
      #     echo "inputs=${{ toJson(inputs) }}"
      #     echo "github.event=${{ toJson(github.event) }}"

      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          persist-credentials: true

      - name: Run sitemap action
        id: test
        uses: ./.github/actions/k6-sitemap
        with:
          base_url: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.BASE_URL) || (github.event_name == 'schedule' && 'https://nclsbayona.github.io') || (github.event_name == 'workflow_dispatch' && inputs.base_url) || (github.event_name == 'push' && 'https://nclsbayona.github.io') || (github.event_name == 'deployment' && inputs.base_url) }}
          sitemap_url: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.SITEMAP_URL) || (github.event_name == 'schedule' && 'https://nclsbayona.github.io/sitemap.xml') || (github.event_name == 'workflow_dispatch' && inputs.sitemap_url) || (github.event_name == 'push' && 'https://nclsbayona.github.io/sitemap.xml') || (github.event_name == 'deployment' && inputs.sitemap_url) }}
          vus: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.VUS) || (github.event_name == 'schedule' && '50') || (github.event_name == 'workflow_dispatch' && inputs.users) || (github.event_name == 'push' && '10') || (github.event_name == 'deployment' && inputs.users) }}
          duration: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.DURATION) || (github.event_name == 'schedule' && '5m') || (github.event_name == 'workflow_dispatch' && inputs.duration) || (github.event_name == 'push' && '30s') || (github.event_name == 'deployment' && inputs.duration) }}
          http_timeout: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.HTTP_TIMEOUT) || (github.event_name == 'schedule' && '5s') || (github.event_name == 'workflow_dispatch' && inputs.http_timeout) || (github.event_name == 'push' && '5s') || (github.event_name == 'deployment' && inputs.http_timeout) }}
          url_limit: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.URL_LIMIT) || (github.event_name == 'schedule' && '500') || (github.event_name == 'workflow_dispatch' && inputs.url_limit) || (github.event_name == 'push' && '500') || (github.event_name == 'deployment' && inputs.url_limit) }}

      - name: Get dashboard variables
        id: dashboard
        run: |
          echo "The HTML is available at ${{ steps.test.outputs.dashboard_html }}"
          echo "The PNG is available at ${{ steps.test.outputs.dashboard_png }}"

      - name: Download dashboard artifacts
        id: download_png
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ steps.test.outputs.artifact }}

      - name: Add safe directory
        run: |
          git config --global --add safe.directory /__w/nclsbayona.github.io/nclsbayona.github.io && rm -rf results

      - name: Commit dashboard PNG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: :memo: Update load test dashboard"