name: Update theme
run-name: ${{ github.workflow }} (#${{ github.run_id }})

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/update-theme.yml'
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-theme:
    runs-on: ubuntu-latest
    name: Update theme
    env:
      PR_BRANCH: "update-theme-${{ github.run_id }}"

    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v7.0.0
        with:
            persist-credentials: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.140.2"
          extended: true

      - name: Update theme
        run: hugo mod get -u github.com/CaiJimmy/hugo-theme-stack/v3

      - name: Tidy go.mod, go.sum
        run: hugo mod tidy

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          token: ${{ secrets.PR_TOKEN }}
          branch: ${{ env.PR_BRANCH }}
          base: main
          delete-branch: true
          commit-message: "chore: Update theme"
          title: "ci: :arrow_up: Update theme"
          body: "Automated update: update theme"
