name: Update README with contributors
run-name: ${{ github.workflow }} (#${{ github.run_id }})

on:
    workflow_dispatch:
    workflow_call:

jobs:
  update-readme:
    name: Update README with contributors
    runs-on: ubuntu-latest
    steps:
    - name: Contribute List
      uses: akhilmhdh/contributors-readme-action@v2.3.11
      env:
        GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
      with:
        columns_per_row: 2
        use_username: true
        pr_title_on_protected: docs: contributors readme action update
