name: Verify PR
run-name: ${{ github.workflow }} (#${{ github.run_id }})

on: 
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

env:
  PR_URL: ${{github.event.pull_request.html_url}}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  review-title:
    name: Review PR title
    runs-on: ubuntu-latest
    steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - uses: thehanimo/pr-title-checker@v1.4.3
        id: check
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-config.json
      
      - name: Add comment to fix PR title
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.check.outputs.success == 'false'}}
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### 🚨 PR Title Needs Formatting
              The title of this PR needs to be formatted correctly and include an Azure Boards Reference. 
              Please update the title to match the format `type: description AB#xxx`. Examples:
              * `bugfix: fix typo in README.md AB#123`
              * `chore: update dependencies AB#456`
              * `feat: add new feature AB#789`
              * `chore: fixing build pipeline` - no AB reference

      - name: Add comment that PR title is fixed
        if: ${{ steps.check.outputs.success == 'true'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### ✅ PR Title Formatted Correctly
              The title of this PR has been updated to match the correct format. Thank you!
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    permissions: {}
    needs: review-title
    concurrency:
        group: link_check-${{ github.ref }}
        cancel-in-progress: false
    steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html'
          format: markdown
          jobSummary: true
          output: 'lychee-report.md'
          fail: false
          failIfEmpty: false
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Upload Link Checker Report
        uses: actions/upload-artifact@v7.0.1
        with:
          name: link-checker-report
          path: lychee-report.md

  review-gif-pr:
    runs-on: ubuntu-latest
    needs: link-checker
    name: Automatically merge GIF PRs
    if: |
      github.event.pull_request.user.login == 'nclsbayona' && 
      github.event.pull_request.title == 'docs: :memo: Update website gif'
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

    - name: Merge GIF PRs
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a new GIF generated by the workflow**"
        gh pr merge --auto --merge "$PR_URL"

  review-theme-pr:
    runs-on: ubuntu-latest
    needs: link-checker
    name: Automatically merge theme PRs
    if: |
      github.event.pull_request.user.login == 'nclsbayona' && 
      github.event.pull_request.title == 'ci: :arrow_up: Update theme'
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

    - name: Merge GIF PRs
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a new GIF generated by the workflow**"
        gh pr merge --auto --merge "$PR_URL"

  review-quote-pr:
    runs-on: ubuntu-latest
    needs: link-checker
    name: Automatically merge quote PRs
    if: |
      github.event.pull_request.user.login == 'nclsbayona' && 
      github.event.pull_request.title == 'chore: :hammer: Update quote of the day'
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

    - name: Merge quote PRs
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a new GIF generated by the workflow**"
        gh pr merge --auto --merge "$PR_URL"

  review-loadtest-pr:
    runs-on: ubuntu-latest
    needs: link-checker
    name: Automatically merge loadtest PRs
    if: |
      github.event.pull_request.user.login == 'nclsbayona' && 
      github.event.pull_request.title == 'docs: :memo: Update loadtest image'
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

    - name: Merge loadtest PRs
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a new loadtest image generated by the workflow**"
        gh pr merge --auto --merge "$PR_URL"

  review-contributor-pr:
      runs-on: ubuntu-latest
      needs: link-checker
      name: Automatically merge contributor PRs
      if: |
        github.event.pull_request.user.login == 'nclsbayona' && 
        github.event.pull_request.title == 'docs(contributor): contributors readme action update'
      steps:
      # - name: Configure monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: Merge contributor PRs
        run: |
          gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes an update to the contributors readme**"
          gh pr merge --auto --merge "$PR_URL"

  review-dependabot-pr:
    runs-on: ubuntu-latest
    needs: link-checker
    name: Automatically merge Dependabot PRs
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
    # - name: Configure monitor
    #   uses: GitHubSecurityLab/actions-permissions/monitor@v1
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v3.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        compat-lookup: true

    - name: Comment on major updates of non-development dependencies if the compatibility score is less than 70
      if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' && steps.dependabot-metadata.outputs.compatibility-score < 70}}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr comment $PR_URL --body "I'm **not approving** this PR because **it includes a major update of a dependency used in production and compatibility is less than 70**"
        exit 0

    - name: Add dependency update labels
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr edit $PR_URL --add-label "dependencies"
        gh pr edit $PR_URL --add-label "enhancement"

    - name: Comment on patch and minor updates
      if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'}}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"

    - name: Comment on major updates of development dependencies
      if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:development'}}
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a major update of a dependency used only in development**"

    - name: Comment on major updates of production dependencies with compatibility score greater than 70
      if: ${{steps.dependabot-metadata.outputs.compatibility-score > 70}}
      run: |
        gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a major update of a dependency used in production but compatibility is greater than *70%***"

    - name: Merge Dependabot PRs
      env:
        GH_TOKEN: ${{ secrets.PR_TOKEN }}
      run: |
        gh pr merge --auto --merge "$PR_URL"
